### ISSUE TITLE
postcss + css modules + extracted styles

### ISSUE THREAD

**Issue by lancetharper** [vuejs/rollup-plugin-vue#203]
### Relevant SFC code:

```
<template>
<div :class="$style.test"> <!-- turns into "test___abc" -->
  <p :class="$style.local">CLASS HERE IS EMPTY</p>
</div>
</template>

<style module>
@import 'path/to/globals.pcss'
@import 'localStyle.pcss'

.test {
  background: purple;
}
</style>
```
### Relevant parts of rollup config:

```
VuePlugin({
  css: false,
  defaultLang: { 
    style: 'postcss'
  },
}),
PostcssPlugin({
  extract: `out.css`,
  modules: {
    generateScopedName: `[local]___abc`,
  }
}),
```

Classes from `localStyle.pcss` are never applied via the `$style` object thus my component has empty classes that should be css-module classes. The css in the output file is all correct (as expected).

It's obvious the imported styles are never considered because the styles haven't been processed by postcss.

### Also tried:

Having `rollup-plugin-vue` handle the postcss by adding this to the config (where `postcssConfig` comes from my postcssrc file:
```
style: {
  postcssOptions: postcssConfig.options,
  postcssPlugins: postcssConfig.plugins,
  postcssModulesOptions: {
    generateScopedName: `[local]___abc`,
  }
},
```
but this results in an error `Error: Use process(css).then(cb) to work with async plugins`

This has worked fine with `vue-loader` + webpack. 

How is this supposed to work for this plugin? I'm exploring rollup as a replacement for webpack to build a component library so this is all fairly new to me. Any help is appreciated!

**Comment by gregorskii** [comment]
+1

**Comment by fedesigner** [comment]
+1

**Comment by channg** [comment]
+1  me too

**Comment by keiww** [comment]
+1

**Comment by znck** [comment]
Fixed. To be released soon.

**Comment by lancetharper** [comment]
As far as I can tell, this has not been fixed. The `@import xyz` are still not resolved.
